variables:
  VERSION: pipeline${CI_PIPELINE_IID}-${CI_COMMIT_SHORT_SHA}
  ECR: 241219621310.dkr.ecr.eu-west-1.amazonaws.com/numberfour

image: ${ECR}/scala-build-images:openjdk11-scala2.12-sbt1.2

cache:
  key: one-cache-per-project
  paths:
    - cache/
    - "target/*/resolution-cache"
    - "*/target/*/resolution-cache"

stages:
  - build-test
  - publish

build and test:
  stage: build-test
  script:
    - sbt coverage testOnly coverageReport coverageAggregate
  artifacts:
    expire_in: 1 hour
    reports:
      junit:
        - './target/test-reports/*.xml'
        - '**/target/test-reports/*.xml'

publish:
  stage: publish
  script:
    - sed "s/unstable-SNAPSHOT/${CI_COMMIT_TAG}/" build.sbt > build.sbt.2
    - mv build.sbt.2 build.sbt
    - cat build.sbt | grep version
    - sbt publish
  artifacts:
    expire_in: 1 hour
    reports:
      junit:
        - './target/test-reports/*.xml'
        - '**/target/test-reports/*.xml'
  only:
    - tags
