variables:
  VERSION: pipeline${CI_PIPELINE_IID}-${CI_COMMIT_SHORT_SHA}
  ECR: 241219621310.dkr.ecr.eu-west-1.amazonaws.com/numberfour
  SBT_OPTS: '-Dsbt.ivy.home=cache/ivy'

image: ${ECR}/scala-build-images:openjdk11-scala2.12-sbt1.2

cache:
  key: one-cache-per-project
  paths:
    - cache/
    - "target/*/resolution-cache"
    - "*/target/*/resolution-cache"

stages:
  - build-test-publish

build and test and publish:
  stage: build-test-publish
  script:
    - sbt coverage testOnly coverageReport coverageAggregate
    - if [ ! -z $CI_COMMIT_TAG ]; then export VERSION=$CI_COMMIT_TAG ; fi
    - sed "s/unstable-SNAPSHOT/${VERSION}/" build.sbt > build.sbt.2
    - mv build.sbt.2 build.sbt
    - cat build.sbt | grep version
    - sbt publish   # publish must be separate from coverage
  artifacts:
    expire_in: 1 hour
    reports:
      junit:
        - './target/test-reports/*.xml'
        - '**/target/test-reports/*.xml'
